key(ctrl-left):"snap left"
key(shift-left)"snap left third"
key(ctrl-shift-left)"snap left two thirds"
key(ctrl-right):"snap right"
key(right-shift):"snap right third"
key(ctrl-right-shift):"snap right two thirds"
